---
title: "Resources"
output: html_document
---
See the [online workshop notes](https://tesaunders.github.io/reproducible-r/) to revisit the lesson in your own time.

[Happy Git with R](https://happygitwithr.com/) is an online resource for getting R/RStudio set up to use Git & GitHub, and contains lots of useful information about working with R/RStudio and Git/GitHub on a daily basis. 

[Version control with Git](https://uoa-eresearch.github.io/git-novice/) provides a proper introduction to version control using Git and GitHub. It focuses mostly on using Git from the commandline which is a good way to learn, but you'll probably be using Git from within RStudio most of the time - see the lesson for a supplemental episode on this topic.

[R for Data Science](https://r4ds.hadley.nz/) is highly recommended as a general purpose introduction to R, and particularly the Tidyverse ecosystem of packages. 

[Tidy data](https://uoa-eresearch.github.io/tidy-data/) expands on some of the principles we talked about around keeping files and analyses organised.

See the [renv documentation](https://rstudio.github.io/renv/) for an overview of how to use renv with your projects.

[The Turing Way](https://book.the-turing-way.org/) is an online handbook outlining how to do reproducible, ethical and collaborative data science. It contains information on a wide variety of topics we have touched on in this workshop, including publishing data and code.

